Upgrade linting to v2.1.0 (#73)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,95 +1,204 @@
 #!/bin/bash
 
 # Directories containing Node.js projects to be linted.
-node_dirs=(frontend backend)
+node_dirs=(backend frontend)
 
-# Command to run in each directory specified in node_dirs.
-lint_command=(npm run lint-check)
+# Command used to run a lint check.
+check_command=(npm run lint-check)
 
-# Uncomment the line below to disable linting.
-#lint_command=(true)
+# Uncomment the line below to disable linting for testing purposes.
+#check_command=(pwd)
+
+# Command used to autofix lint errors.
+fix_command=(npm run lint-fix)
+
+setaf3="$(tput setaf 3 2> /dev/null)"
+setaf1="$(tput setaf 1 2> /dev/null)"
+sgr0="$(tput sgr0 2> /dev/null)"
 
 log() {
 	echo "${0}:" "${@}" >&2
 }
 
-die() {
-	log "${@}"
-	exit 1
+warn() {
+	log "${setaf3}${@}${sgr0}"
 }
 
-num_stashes() {
-	git stash list | wc -l
+error() {
+	log "${setaf1}${@}${sgr0}"
 }
 
-# Make the working directory match the staging area.
-stash_push() {
-	log "Stashing unstaged changes."
-
-	local stashes_before=$(num_stashes)
-	git stash push --include-untracked --keep-index &> /dev/null
-	local stashes_after=$(num_stashes)
-
-	case "$(( stashes_after - stashes_before ))" in
-		1)
-			log "Stashing successful."
-			return 0
+parse_yes_no() {
+	case "${1}" in
+		[yY]|[yY][eE][sS])
+			echo "yes"
 			;;
-		0)
-			log "Nothing to stash."
-			return 1
+		[nN]|[nN][oO])
+			echo "no"
+			;;
+		"")
+			echo ""
 			;;
 		*)
-			die "Something unexpected occurred." \
-				"There used to be ${stashes_before} stash entries;" \
-				"now there are ${stashes_after}." \
-				"You'll need to manually recover your changes from the stash."
-			;;
+			echo "invalid"
 	esac
 }
 
-# Restore unstaged changes to the working directory.
-stash_pop() {
-	log "Restoring unstaged changes."
+ask_yes_no() {
+	local prompt="${1}"
+	local default_selection="$(parse_yes_no "${2}")"
 
-	if git stash pop &> /dev/null; then
-		log "Unstaged changes restored."
-		return 0
-	else
-		die "An unexpected error occurred." \
-			"Resolve the conflicts by hand, then run 'git stash drop'."
+	local yn_letters
+	local default_status
+	case "${default_selection}" in
+		yes)
+			yn_letters="Y/n"
+			default_status=0
+			;;
+		no)
+			yn_letters="y/N"
+			default_status=1
+			;;
+		*)
+			error "An internal error occurred."
+			error " The default selection is missing or invalid."
+			exit 1
+			;;
+	esac
+
+	prompt+=" [${yn_letters}] "
+
+	if (( !interactive )); then
+		log "${prompt}"
+		warn "Skipping interactive prompt (stdin not available)."
+		warn " Choosing default selection '${default_selection}'."
+		return "${default_status}"
+	fi
+
+	local selection
+	while :; do
+		read -p "${0}: ${prompt}" selection
+		selection="$(parse_yes_no "${selection}")"
+
+		case "${selection}" in
+			yes)
+				return 0
+				;;
+			no)
+				return 1
+				;;
+			'')
+				return "${default_status}"
+				;;
+			*)
+				warn "Invalid input."
+				log " Please type 'y' or 'n' and press Enter."
+				;;
+		esac
+	done
+}
+
+explain_no_verify() {
+	log "If you wish to bypass the lint check entirely,"
+	log "use the following command:"
+	log "    git commit --no-verify"
+}
+
+dir_check() {
+	for dir in "${node_dirs[@]}"; do
+		if ! [ -d "${dir}" ]; then
+			error "Directory '${dir}' does not exist. Please"
+			error " edit the 'node_dirs' variable in '${0}'."
+			exit 1
+		fi
+	done
+}
+
+autocrlf_check() {
+	local core_autocrlf="$(git config --get core.autocrlf || echo "false")"
+	if [ "${core_autocrlf}" != "false" ]; then
+		warn "core.autocrlf is set to '${core_autocrlf}' in the git config."
+		warn " This might produce CRLF line endings in the working"
+		warn " tree when Prettier expects LF. This can be fixed by"
+		warn " running the following command:"
+		warn "    git config core.autocrlf false"
+	fi
+}
+
+unstaged_changes_check() {
+	if git status --porcelain | grep -qv '^[MARCD] '; then
+		git status
+
+		warn "The working tree has unstaged changes, which"
+		warn " may result in an incorrect lint check result."
+		if ! ask_yes_no "Proceed with lint check anyway?" "no"; then
+			log "Please stage (or stash) any unstaged changes,"
+			log " then try again."
+			exit 1
+		fi
 	fi
 }
 
 lint_check() {
+	local failed_dirs=()
 	for dir in "${node_dirs[@]}"; do
-		if ! [ -d "${dir}" ]; then
-			log "Directory '${dir}' does not exist." \
-				"Edit this script and change 'node_dirs'."
-			return 1
-		fi
-
-		if ! (cd "${dir}" && "${lint_command[@]}"); then
-			log "Lint check failed." \
-				"Run 'npm run lint-fix', then manually fix any remaining errors." \
-				"To skip this lint check, use 'git commit --no-verify'."
-			return 1
+		log "Running lint check in '${dir}'..."
+		if ! (cd "${dir}" && "${check_command[@]}"); then
+			failed_dirs+=("${dir}")
 		fi
 	done
 
-	log "Lint check passed."
-	return 0
+	if (( ${#failed_dirs[@]} == 0 )); then
+		log "Lint check passed."
+		return 0
+	fi
+
+	warn "Lint check failed in the following directories:"
+	warn "   $(printf ' %q' "${failed_dirs[@]}")"
+
+	if ask_yes_no "Proceed with commit anyway?" "no"; then
+		return 0
+	fi
+
+	log "The lint autofix command is:"
+	log "   $(printf ' %q' "${fix_command[@]}")"
+	if ask_yes_no "Run this command in each failed directory?" "yes"; then
+		for dir in "${failed_dirs[@]}"; do
+			log "Running autofix command in '${dir}'..."
+			(cd "${dir}" && "${fix_command[@]}")
+		done
+
+		log "Please manually fix any remaining lint errors,"
+		log " then stage your changes and try again."
+	else
+		log "Please fix the lint errors, then stage your"
+		log " changes and try again."
+	fi
+
+	explain_no_verify
+	return 1
+}
+
+cancel() {
+	>&2 echo
+	log "Lint check canceled."
+	explain_no_verify
+	exit 0
 }
 
 main() {
-	if [ -f '.git/MERGE_HEAD' ]; then
-		log "WARNING: unable to stash unstaged changes during merge." \
-			"If there are unstaged changes, they may result in an" \
-			"incorrect lint check result."
-	else
-		stash_push && trap stash_pop EXIT
+	trap cancel SIGINT
+	log "Starting lint check. Use Ctrl+C to cancel."
+
+	interactive=1
+	if ! exec < /dev/tty; then
+		warn "Cannot open stdin. Disabling interactive prompts."
+		interactive=0
 	fi
 
+	dir_check
+	autocrlf_check
+	unstaged_changes_check
 	lint_check
 }
 
