Pop from stash if pre-commit check is interrupted

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Directories containing Node.js projects to be linted.
-node_dirs=(backend frontend)
+node_dirs=(frontend backend)
 
 # Command to run in each directory specified in node_dirs.
 lint_command=(npm run lint-check)
@@ -27,7 +27,7 @@ stash_push() {
 	log "Stashing unstaged changes."
 
 	local stashes_before=$(num_stashes)
-	git stash push --include-untracked --keep-index
+	git stash push --include-untracked --keep-index --quiet
 	local stashes_after=$(num_stashes)
 
 	case "$(( stashes_after - stashes_before ))" in
@@ -52,7 +52,7 @@ stash_push() {
 stash_pop() {
 	log "Restoring unstaged changes."
 
-	if git stash pop; then
+	if git stash pop --quiet; then
 		log "Unstaged changes restored."
 		return 0
 	else
@@ -61,24 +61,30 @@ stash_pop() {
 	fi
 }
 
-main() {
-	stash_push
-	local stash_push_status="${?}"
-
+lint_check() {
 	for dir in "${node_dirs[@]}"; do
-		[ -d "${dir}" ] || die \
-			"Directory '${dir}' does not exist." \
-			"Edit this script and change 'node_dirs'."
+		if ! [ -d "${dir}" ]; then
+			log "Directory '${dir}' does not exist." \
+				"Edit this script and change 'node_dirs'."
+			return 1
+		fi
 
-		(cd "${dir}" && "${lint_command[@]}") || die \
-			"Lint check failed." \
-			"Run 'npm run lint-fix', then manually fix any remaining errors." \
-			"To skip this lint check, use 'git commit --no-verify'."
+		if ! (cd "${dir}" && "${lint_command[@]}"); then
+			log "Lint check failed." \
+				"Run 'npm run lint-fix', then manually fix any remaining errors." \
+				"To skip this lint check, use 'git commit --no-verify'."
+			return 1
+		fi
 	done
 
 	log "Lint check passed."
+	return 0
+}
 
-	(( stash_push_status == 0 )) && stash_pop
+main() {
+	stash_push && trap stash_pop EXIT
+
+	lint_check
 }
 
 main "${@}"
